name: Run MATLAB Tests

on: [push]

jobs:
  all-tests:
    name: Run All MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2.5.0
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: addpath( "src" ); addpath( "test" ); RunAllTests